### PR TITLE
Create custom theme feature, starting point for environment initialization script

### PR DESCRIPTION
**Pull request by dhruvkrishnavaid**
Custom themes can be implemented through the backend using `selected` field.
Create color objects in the database and set `selected` to `true` to enable the theme. Fallback and defaults to violet.

### CODE REVIEW

**Review by dhruvkrishnavaid — COMMENTED** [review]
The initialization file is ready!
Just set the environment variables in `backend/.env` and run `yarn initialize` either from project root or from `backend` directory.
It will connect to the database, create a table named `colors`, create all the color objects, and set `selected` to `true` where `name = violet`. All other colors will have `selected` as `false`.

**Review by iskcon-noida — CHANGES_REQUESTED** [review]
@dhruvkrishnavaid Please remove .yarn changes from this PR. And also remove these warnings. Due to which issues occur in the docker container.

image

**Comment by dhruvkrishnavaid** [comment]
Prabhu I guess the code stored locally on your system is outdated.
Try running git pull once, the warnings should be removed from the console.

**Comment by iskcon-noida** [comment]
@dhruvkrishnavaid Still there are an issue in docker build. Before the git pull, docker able to successfully build the image and only issue occurs in backend container. But after the git pull, Docker cannot able to build image. It's showing this error on `yarn install`. Please check it.

image

**Comment by dhruvkrishnavaid** [comment]
Yarnrc updated. Please check again, the issue should be resolved.

**Review by iskcon-noida — APPROVED** [review]
Ready to Merge

**Pull request merged**
